#!/usr/bin/env zsh
# @(#)[argc 2016/10/25 07:47:28 tw@csongor.lan]
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh

echo $#

# Copyright © 2016 by Tom Davis <tom@greyshirt.net>.
