#!/usr/bin/env zsh
# $Id: argc,v 1.2 2016/10/25 07:47:28 tw Exp $
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh

echo $#

# Copyright © 2016 by Tom Davis <tom@greyshirt.net>.
