#!/usr/bin/env zsh
# @(#)[go 2016/10/25 07:47:28 tw@csongor.lan]
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh

[[ $PWD =~ ${1:-::} ]]&& { warn '$PWD matches. Doing nothing.'; return 1; }
[[ $PWD =~ ${2:-::} ]]&& { warn '$PWD matches. Doing nothing.'; return 1; }

eval "$( $LOCALBIN/go $@ )"

# Copyright (C) 2016 by Tom Davis <tom@greyshirt.net>.
