#!/usr/bin/env zsh
# $Id: msg:subj,v 1.4 2016/10/25 07:47:28 tw Exp $
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh
setopt local_options local_traps pipe_fail bsd_echo
setopt numeric_glob_sort null_glob

typeset -ga MSGs=()
typeset -- OLDPWD=$PWD
cd $(mhpath)

typeset -a msgList=( [1-9]* )
(($#msgList))|| {
	echo "msg:from: no message in $(folder -fast)" >&2
	cd $OLDPWD
	return
  }

typeset -a showcmd=(
	'{printf( "%-4s %s\n", FILENAME, $0 ); nextfile;}'
  )
typeset -- Q="${1:+ && /$1/}"
typeset -- EOH=""
(($#))||   EOH="${1:-printf(\"%-4s %s\n\",FILENAME,\"<X Subject:>\"); }"

typeset -a awkpgm=(
	"/^Subject:/$Q"			'{sub(/^Subject: */,"");'"$showcmd}"
	'/^$/'					"{${EOH/X/no}nextfile;}"
  )
# if we get to the body without a match, show that, unless we're looking 
# for a particular pattern, in which case no Subject doesn't match

#print -r -- "$awkpgm"
#return

awk "$awkpgm" $msgList | while read -r ln; do
	echo "$ln"
	[[ $ln =~ [[:digit:]]+ ]]&& MSGs+=( $MATCH )
done

cd $OLDPWD

# Copyright © 2016 by Tom Davis <tom@greyshirt.net>.
