#!/usr/bin/env zsh
# @(#)[:Yrzqz+R5Y8|?zZ^uwB80: 2017/03/05 05:45:04 tw@csongor.lan]
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh

(($#))&& -warn 'Discarding all parameters.' "$@"

# there's a function for that
ssh sam.lan


# Copyright © 2016 by Tom Davis <tom@greyshirt.net>.
