#!/usr/bin/env zsh
# @(#)[sam 2016/10/25 07:47:28 tw@csongor.lan]
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh

(($#))&& -warn 'Discarding all parameters.' "$@"

# there's a function for that
ssh sam.lan

# Copyright © 2016 by Tom Davis <tom@greyshirt.net>.
