#!/usr/bin/env zsh
# $Id: uberbaud,v 1.2 2016/10/25 07:47:28 tw Exp $
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh

(($#))&& -warn 'Discarding all parameters.' "$@"

# there's a function for that
ssh uberbaud.net

# Copyright © 2016 by Tom Davis <tom@greyshirt.net>.
