#!/usr/bin/env zsh
# @(#)[:lqiGg2*{XZZn8Nx0qB=7: 2017/03/05 05:45:32 tw@csongor.lan]
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh

(($#))&& -warn 'Discarding all parameters.' "$@"

# there's a function for that
ssh uberbaud.net


# Copyright © 2016 by Tom Davis <tom@greyshirt.net>.
