#!/usr/bin/env zsh
# @(#)[:<Kd-7|aF~Qu7)M`*f0ry: 2017/03/05 05:45:38 tw@csongor.lan]
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh

[[ $# -eq 0 ]] && set '%F{251}[No message provided.]%f'

print -Plu 2 "  %F{4}Usage%f: $1" "         ${(@)^argv[2,-1]}"

errno=0
kill -SIGINT $$


# Copyright (C) 2016 by Tom Davis <tom@greyshirt.net>.
