#!/usr/bin/env zsh
# @(#)[:5V,y(}-;oUC42~pl69?_: 2017/03/05 05:37:40 tw@csongor.lan]
# vim: filetype=zsh tabstop=4 textwidth=72 noexpandtab

emulate -L zsh


(($#))&& warn 'Discarding all parameters.' "$*"

# there's a function for that
ssh yt.lan

# Copyright © 2016 by Tom Davis <tom@greyshirt.net>.
