# Generated by `rezcompall.zsh`. Any edits will be overwritten!

emulate -L zsh
setopt bsd_echo extended_glob local_options local_patterns local_traps no_hash_dirs no_mult_ios no_unset pipe_fail re_match_pcre

fpath=( $USR_ZSHLIB/common_funcs.zwc $fpath )
autoload -Uz -- --msgify -die -notify -usage -warn :assign :git:current:branch :git:on:master :git:where:am:i :hide-cursor :istat :progress-bar :rootness:cmd :rootness:filter:cmd :rootness:finit :rootness:init :set:A-minus-B :set:intersect :set:union :show-cursor :up-conky-note :vim-recover-file :vim-swap-file-name :vim-swap-info :x11-get-winid-from-pid :yes-or-no readlink

alias on_error='((!$?))||'
alias on-error='((!$?))||'
alias if-no='((!$?))||'
alias if-yes='(($?))||'
