# @(#)[:O|k_cRl#UUzvO{A*dk~u: 2017/03/05 06:25:19 tw@csongor.lan]
# system wide ZSHELL file that is ALWAYS called

if [[ -d ~/.config ]]; then
	XDG_CONFIG_HOME=~/.config
	if [[ -f $XDG_CONFIG_HOME/user-dirs.dirs ]]; then
		. $XDG_CONFIG_HOME/user-dirs.dirs
	fi
	typeset -xm 'XDG_*'

	if [[ -d $XDG_CONFIG_HOME/zsh ]]; then
		ZDOTDIR=$XDG_CONFIG_HOME/zsh
	fi
fi

# vim: filetype=zsh ts=4
# Copyright © 2017 by Tom Davis <tom@greyshirt.net>.
